# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_Phi_hat <- function(N, parameters) {
    .Call('_ParametricHighOrderPortfolios_compute_Phi_hat', PACKAGE = 'ParametricHighOrderPortfolios', N, parameters)
}

compute_Psi_hat <- function(N, parameters) {
    .Call('_ParametricHighOrderPortfolios_compute_Psi_hat', PACKAGE = 'ParametricHighOrderPortfolios', N, parameters)
}

